services:
  - type: web
    name: documorph-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && playwright install chromium"
    startCommand: "bash start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
